version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: koa.mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: koa
      MYSQL_USER: koa
      MYSQL_PASSWORD: 1
    ports:
    - 3307:3306
  adminer:
    image: asergey/adminer:latest
    container_name: koa.adminer
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 1
    ports:
    - 3308:80
    links:
    - mysql
    logging:
      driver: none